In [22]:
import numpy as np
import scipy.linalg as la
import matplotlib.pyplot as plt
from numpy.linalg import matrix_power

### Best Case Scenario

In [3]:
B = np.array([[0.63, 0.63, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2], 
[0.34, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
[0, 0.71, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0.71, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
[0, 0, 0, 0.71, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0.71, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0.71, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0.71, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0.71, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 0.71, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0.71, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.71, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.71, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.71, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.71, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.71, 0]]
)

In [63]:
print(B.shape)

(16, 16)


In [64]:
Y, V = la.eig(B)

In [65]:
print(Y)

[ 1.24144022+0.j          0.63891407+0.29119587j  0.63891407-0.29119587j
  0.46798969+0.51244451j  0.46798969-0.51244451j  0.23986627+0.64623213j
  0.23986627-0.64623213j -0.01274413+0.68116868j -0.01274413-0.68116868j
 -0.25762247+0.61653209j -0.25762247-0.61653209j -0.46212066+0.46514502j
 -0.46212066-0.46514502j -0.64489783+0.j         -0.59755397+0.24965983j
 -0.59755397-0.24965983j]


In [66]:
yabs = np.abs(Y)

In [67]:
max(yabs)

1.2414402241505778

In [82]:
### Eigenvector associated with dominant Eigenvalue
print(V[0])

[ 0.9485312 +0.j          0.44155086+0.j          0.44155086-0.j
 -0.40648307+0.j         -0.40648307-0.j          0.38625158+0.j
  0.38625158-0.j          0.35157721+0.j          0.35157721-0.j
 -0.10054223-0.27880184j -0.10054223+0.27880184j -0.18287935-0.16580673j
 -0.18287935+0.16580673j -0.2078037 +0.j         -0.20434097-0.07385038j
 -0.20434097+0.07385038j]


In [69]:
B10 = matrix_power(B, 10)

In [84]:
Binitial = np.array([[0], [100], [50], [50], [25], [10], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0]])

In [71]:
print(Binitial.shape)

(16, 1)


In [72]:
Bfinal = B10 @ Binitial

In [94]:
print(Bfinal/sum(Bfinal))

[[6.09875191e-01]
 [1.67018460e-01]
 [9.55153587e-02]
 [5.46291955e-02]
 [3.12423068e-02]
 [1.78413695e-02]
 [1.01830237e-02]
 [5.92688724e-03]
 [3.54624895e-03]
 [1.65661687e-03]
 [0.00000000e+00]
 [1.09163472e-03]
 [5.45817361e-04]
 [5.45817361e-04]
 [2.72908680e-04]
 [1.09163472e-04]]


### Worst Case Scenario

In [74]:
W = np.array([[0.60, 0.60, 1.15, 1.15, 1.15, 1.15, 1.15, 1.15, 1.15, 1.15, 1.15, 1.15, 1.15, 1.15, 1.15, 1.15], 
[0.32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
[0, 0.68, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0.68, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
[0, 0, 0, 0.68, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0.68, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0.68, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0.68, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0.68, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 0.68, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0.68, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.68, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.68, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.68, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.68, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.68, 0]])

In [75]:
print(W.shape)

(16, 16)


In [76]:
H, J = la.eig(W)

In [77]:
print(H)

[ 1.18285182+0.j          0.6117292 +0.27890757j  0.6117292 -0.27890757j
  0.44802335+0.49054862j  0.44802335-0.49054862j  0.22969649+0.61845887j
  0.22969649-0.61845887j -0.01206036+0.65179318j -0.01206036-0.65179318j
 -0.24642711+0.5899047j  -0.24642711-0.5899047j  -0.4421333 +0.44504919j
 -0.4421333 -0.44504919j -0.61703866+0.j         -0.57173484+0.23887342j
 -0.57173484-0.23887342j]


In [78]:
habs = np.abs(H)

In [79]:
max(habs)

1.1828518192421127

In [81]:
### Eigenvector associated with dominant Eigenvalue
print(J[0])

[ 0.9494508 +0.j          0.44703755+0.j          0.44703755-0.j
  0.41102218+0.j          0.41102218-0.j          0.38995667+0.j
  0.38995667-0.j          0.35428039+0.j          0.35428039-0.j
 -0.10161328-0.28046002j -0.10161328+0.28046002j -0.18406689-0.16675723j
 -0.18406689+0.16675723j  0.20908004+0.j         -0.20559484-0.07429886j
 -0.20559484+0.07429886j]


In [83]:
W10 = matrix_power(W, 10)

In [85]:
Winitial = np.array([[0], [100], [50], [50], [25], [10], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0]])

In [86]:
Wfinal = W10 @ Winitial

In [90]:
print(Wfinal/sum(Wfinal))

[[6.11145255e-01]
 [1.65322684e-01]
 [9.50354888e-02]
 [5.46364130e-02]
 [3.14078690e-02]
 [1.80282721e-02]
 [1.03441760e-02]
 [6.05416236e-03]
 [3.63864385e-03]
 [1.70199508e-03]
 [0.00000000e+00]
 [1.14257045e-03]
 [5.71285225e-04]
 [5.71285225e-04]
 [2.85642612e-04]
 [1.14257045e-04]]


In [91]:
caca = np.array([[2], [5], [8]])

In [93]:
caca/sum(caca)

array([[0.13333333],
       [0.33333333],
       [0.53333333]])

### Test

In [11]:
L = np.array([[0, 0.8, 3.5], [0.8, 0, 0], [0, 0.9, 0]])

In [12]:
print(L)

[[0.  0.8 3.5]
 [0.8 0.  0. ]
 [0.  0.9 0. ]]


In [15]:
e, m = la.eig(L)

In [17]:
print(e)

[ 1.516972+0.j         -0.758486+1.04206671j -0.758486-1.04206671j]


In [18]:
print(m)

[[ 0.85249014+0.j         -0.79729604+0.j         -0.79729604-0.j        ]
 [ 0.44957462+0.j          0.29122871+0.40011252j  0.29122871-0.40011252j]
 [ 0.26672685+0.j          0.10621569-0.32883591j  0.10621569+0.32883591j]]


In [19]:
m[0]

array([ 0.85249014+0.j, -0.79729604+0.j, -0.79729604-0.j])

In [27]:
L10 = matrix_power(L, 10)

In [28]:
print(L10)

[[15.71411722 53.85203712 65.25896832]
 [14.91633562 15.71411722 34.60951245]
 [ 8.89958892 16.78087757  7.80337152]]
