# Stats 21: Homework 2

## Hector Lugo Barrios

Homework copyright Miles Chen. Problems have been adapted from teh exercises in Think Python 2nd Ed by Allen B. Downey.

The questions have been entered into this document. You will modify the document by entering your code.

Make sure you run the cell so the requested output is visible. Download the finished document as a PDF file. If you are unable to convert it to a PDF, you can download it as an HTML file and then print to PDF.

**Homework is an opportunity to practice coding and to practice problem solving. Doing exercises is where you will do most of your learning.**

**Copying someone else's solutions takes away your learning opportunities. It is also academic dishonesty.**

## Reading

- Chapters 11, 12, and 14

Please keep up with the reading. The chapters are short.

In [129]:
import pandas as pd
import numpy as np

### Exercise 11.1

Write a function that reads the words in `words.txt` and stores them as keys in a dictionary. It doesn't matter what the values are. Then you can use the in operator as a fast way to
check whether a string is in the dictionary.

Use the same `words.txt` file from HW2.

Do Exercise 10.10 but this time searching the dictionary using the `in` operator. You can see how much faster it is to search a dictionary.

In [130]:
def make_word_dict():
    fin = open('words.txt')
    empty = {}
    t = []
    n = 1
    for line in fin:
        word = line.strip()
        t.append(word)
    for i in t:
        empty[i] = n
        n += 1
    return empty

In [131]:
word_dict = make_word_dict()

In [132]:
"hello" in word_dict

True

### Exercise 11.4

In Exercise 10.7, you created a function called `has_duplicates()`. It takes a list as a parameter and returns `True` if there is any object that appears more than once in the list.

Use a dictionary to write a faster, simpler version of `has_duplicates()`.

In [133]:
def has_duplicates(t):
    empty = {}
    for i in t:
        empty[i] = 1
    return len(t) != len(empty)

In [134]:
has_duplicates(['a','b','b','c'])

True

In [135]:
has_duplicates(['a','b','c','a'])

True

In [136]:
has_duplicates(['a', 'b', 'c', 'd', 'e', 'm'])

False

### Exercise 11.5

A Caesar cipher is a weak form of encryption that involves 'rotating' each letter by a fixed number of places. To rotate a letter means to shift it through the alphabet, wrapping around to the beginning if necessary. "A" rotated by 3 is "D". "Z" rotated by 1 is "A".

Two words are "rotate pairs" if you can rotate one of them and get the other. For example, "cheer" rotated by 7 is "jolly".

Write a script that reads in the wordlist `words.txt` and finds all the rotate pairs of words that are 5 letters or longer.

One function that could be helpful is the function `ord()` which converts a character to a numeric code. Keep in mind that numeric codes for uppercase and lowercase letters are different.

Some hints:

- you can write helper functions, such as a function that will rotate a letter by a certain number and/or another function that will rotate a word by a number of letters
- to keep your script running quickly, you should use the wordlist dictionary from exercise 11.1

In [49]:
def rotation(word, number):
    rotated = ''
    for letter in word.lower():
        if (ord(letter) + number) > 122:
            a = ord(letter) + number
            x = a - 122
            temp = chr(96 + x)
            #print(letter, "temp", temp)
            rotated = rotated + temp
        else:
            rotated = rotated + chr(ord(letter) + number) 
    return rotated

def moreThan5():
    empty = {}
    n = 1
    for i in word_dict.keys():
        if len(i) >= 5:
            empty[i] = n
            n += 1
    return empty

new = moreThan5()
for i in new.keys():
    for k in new.keys():
        for j in range(1, 26):
            if (rotation(i, j) == k):
                print(i, "is a rotate pair of", k)

I tried running the above code, but the kernel stopped working every time. Then I tried it with a different text file with less words and it worked fine. I could not get it to work for the `words.txt` file. :(

In [137]:
print("a rotated by 26 is", rotation("a", 26))
print("a rotated by 25 is", rotation("a", 25))

a rotated by 26 is a
a rotated by 25 is z


### Exercise 12.2

Write a program that reads a word list from a file (see Section 9.1) and finds all the sets of words that are anagrams.

After finding all anagram sets, print the list of all anagram sets that have 6 or more entries in it.

Here is an example of what the output might look like:

~~~
['abets', 'baste', 'bates', 'beast', 'beats', 'betas', 'tabes']
['acers', 'acres', 'cares', 'carse', 'escar', 'races', 'scare', 'serac']
['acred', 'arced', 'cadre', 'cared', 'cedar', 'raced']
...
~~~

Hint:

First traverse the entire wordlist to build a dictionary that maps from a collection of letters to a list of words that can be spelled with those letters. The question is, how can you represent the collection of letters in a way that can be used as a key? i.e. The word "eat" and the word "tea" should be in a list associated with a key ('a','e','t').

In [138]:
def is_anagram(word1, word2):
    isAnagram = False
    plain1 = word1.replace(" ","").lower()
    plain2 = word2.replace(" ","").lower()
    #print(sorted(plain1))
    #print(sorted(plain2))
    if sorted(plain1) == sorted(plain2):
        isAnagram = True
    else:
        isAnagram = False
    return isAnagram

def anagramSets():
    empty = []
    for j in word_dict.keys():
            if (is_anagram("acers", j)):
                empty.append(j)
                if len(empty) >= 7:       
                    print(empty)

test = {"acers":1, "acres":2, "cares":3, "nada":4, "perro":5}
for i in range(len(cac.keys())):
    #print("i is", i, "key is", list(cac.keys())[i])
    for j in range(1, len(test.keys())):
        #print(is_anagram(list(test.keys())[i], list(test.keys())[j]))
        pass

anagramSets()


['acers', 'acres', 'cares', 'carse', 'escar', 'races', 'scare']
['acers', 'acres', 'cares', 'carse', 'escar', 'races', 'scare', 'serac']


My idea was to iterate over the dictionary keys and test the function `is_anagram`. Unfortunately I couldn't figure out how to create a list and append each key that came out True.

### NumPy Exercises

For the following exercises, be sure to print the desired output. You will not receive credit for problems that do not print the desired output.

Some of these exercises will require the use of functions in numpy that may not have been covered in class. Look up documentation on how to use them. I always recommend checking the official reference at https://numpy.org/doc/stable/reference/index.html 

In [139]:
import numpy as np
np.random.seed(1)

#### Exercise NP.1:

Task: Create an array `b` of 10 random integers selected between 0-99

Desired output: `[37 12 72  9 75  5 79 64 16  1]` of course yours might be different

In [140]:
b = np.random.randint(0, 100, 10)
print(b)

[37 12 72  9 75  5 79 64 16  1]


#### NP.1b:

Task: reverse the elements in `b`. Hint: Try slicing the array, but backwards

Desired output: `[ 1 16 64 79  5 75  9 72 12 37]` yours will be different

In [141]:
b[::-1]

array([ 1, 16, 64, 79,  5, 75,  9, 72, 12, 37])

#### NP.2a:

Task: Create an array `c` of 1000 random values selected from a normal distribution centered at 100 with sd = 15, rounded to 1 decimal place. Print only the first 10 values.

Desired output: `[ 92.1  83.9 113.   65.5 126.2  88.6 104.8  96.3 121.9  69.1]` of course your values may be different

In [142]:
sd = 15
mu = 100
c = np.random.normal(mu, sd, 1000)
c_10 = np.round(c[0:10], decimals = 1)
print(c_10)


[ 92.1  83.9 113.   65.5 126.2  88.6 104.8  96.3 121.9  69.1]


#### NP.2b:

Perform a Shapiro-Wilk test to see if the values in c come from a normal distribution. Report the p-value and appropriate conclusion.

Look up `scipy.stats.shapiro` for usage and details.

https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.shapiro.html

In [143]:
from scipy import stats
shapiro_test = stats.shapiro(c)
print("The p-value is:", shapiro_test.pvalue)
print("p-value is greater than 0.05, so we fail to reject null hypothesis. In conclusion, the data comes from a normal distribution.")

The p-value is: 0.18049615621566772
p-value is greater than 0.05, so we fail to reject null hypothesis. In conclusion, the data comes from a normal distribution.


#### NP.2c:

Identify and print the values in `c` that are more than 3 standard deviations from the mean of `c`. Report the proportion of values that are more than 3 sd from the mean.

Desired output: `[ 54.1 ... 148.3 ]`

`0.32 of the values are beyond 3 sd from the mean.`

In [144]:
sd = 15
outliers = c[abs(100-c) >= 3*sd]
print("Values that are more than 3 standard deviations from the mean:", outliers)
#print(len(outliers), len(c))
print((len(outliers)/len(c)), "of the values are beyond 3 sd from the mean")

Values that are more than 3 standard deviations from the mean: [145.46285669 159.37904056 149.81618134  54.19353429]
0.004 of the values are beyond 3 sd from the mean


#### NP.3:

Task: Make a 3x3 identity matrix called `I3`

Desired output: 

~~~
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
~~~

In [145]:
I3 = np.identity(3)
print(I3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### NP.4a:

Task: Make a 10x10 array of values 1 to 100. Call it X

Desired output: 

~~~
[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]
 ~~~

In [146]:
X = np.arange(1, 101).reshape((10, 10))
print(X)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


#### NP.4b:

Task: Make a copy of X, call it Y (1 line). Replace all values in Y that are not squares with 0 (1 line). see `numpy.isin()`

Desired output: 

~~~
[[  1   0   0   4   0   0   0   0   9   0]
 [  0   0   0   0   0  16   0   0   0   0]
 [  0   0   0   0  25   0   0   0   0   0]
...
 [  0   0   0   0   0   0   0   0   0 100]]
 ~~~

In [147]:
Y = X.copy()
Y[~np.isin(Y, [1, 4, 9, 16, 25, 36, 49, 64, 81, 100])] = 0
print(Y)

[[  1   0   0   4   0   0   0   0   9   0]
 [  0   0   0   0   0  16   0   0   0   0]
 [  0   0   0   0  25   0   0   0   0   0]
 [  0   0   0   0   0  36   0   0   0   0]
 [  0   0   0   0   0   0   0   0  49   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0  64   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [ 81   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0 100]]


#### NP.5:

Task: Use `np.tile()` to tile a 2x2 diagonal matrix of integers to make a checkerboard pattern. Call the matrix `checkers`

Desired output: 

~~~
[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 ...
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]
 ~~~

In [148]:
checkers = np.tile([[1, 0],[0,1]] , (4, 4))
print(checkers)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


#### NP.6:

Task: convert the values in `f_temp` from Farenheit to celsius. The conversion is subtract 32, then multiply by 5/9. Round to 1 decimal place.

Desired output: 

~~~
[[21.1 21.7 22.2 22.8 23.3 23.9]
 ...
 [34.4 35.  35.6 36.1 36.7 37.2]]
~~~

In [149]:
# do not modify
f_temp  = np.arange(70,100).reshape((5,6))

In [150]:
fj = (f_temp - 32) * (5/9)
f_temp = np.round(fj, decimals = 1)
print(f_temp)


[[21.1 21.7 22.2 22.8 23.3 23.9]
 [24.4 25.  25.6 26.1 26.7 27.2]
 [27.8 28.3 28.9 29.4 30.  30.6]
 [31.1 31.7 32.2 32.8 33.3 33.9]
 [34.4 35.  35.6 36.1 36.7 37.2]]


#### NP.7:

Task: Convert values in the matrix `x` into z-scores by column, call it matrix `z`. That is: each column should have a mean of 0 and std of 1. (subtract the column mean, and divide by the column std). (not required, but see if you can do this in one line)

Print the column means and column std to show that they have been standardized.

Desired output: 

~~~
[[-1.09996745 -0.47901666  0.8816739 ]
 [ 0.9495002   1.18844641  0.11324252]
...
 [-0.60705751 -1.08536687 -0.57430135]
 [-1.28156585 -0.81250928  1.52877401]]
 
 [ 6.66133815e-17  1.11022302e-16 -1.11022302e-16]
[1. 1. 1.]
~~~

In [151]:
# do not modify
np.random.seed(100)
x = np.random.randint(100, size = 30).reshape(10,3)

In [152]:
x_z = (x - np.mean(x, axis = 0))/np.std(x, axis = 0)
print(x_z)

[[-1.09996745 -0.47901666  0.8816739 ]
 [ 0.9495002   1.18844641  0.11324252]
 [-1.04808219  1.64320907  0.27501755]
 [ 1.23486912  0.40019114  0.84123014]
 [ 1.23486912 -0.78219177 -0.45297008]
 [-0.68488539 -0.75187426  0.5985676 ]
 [ 0.19716398 -0.72155675 -1.46406399]
 [ 1.10515598  1.40066898 -1.74717029]
 [-0.60705751 -1.08536687 -0.57430135]
 [-1.28156585 -0.81250928  1.52877401]]


In [153]:
print(np.mean(x_z, axis = 0))
print(np.std(x_z, axis = 0))

[ 4.44089210e-17  1.11022302e-16 -1.11022302e-16]
[1. 1. 1.]


#### NP.8:

Task: Convert values in the matrix `x` into scaled values from 0 to 10. That is take each column and scale values linearly so that the largest value is 10, and the smallest value in the column is 0. Round results to 2 decimal places. Call the result `y`

(Not required, but see if you can do the calculations in one line.)

Desired output: 

~~~
[[ 0.72  2.22  8.02]
 [ 8.87  8.33  5.68]
...
 [ 2.68  0.    3.58]
 [ 0.    1.   10.  ]]
 ~~~

In [154]:
# do not modify
np.random.seed(100)
x = np.random.randint(100,size = 30).reshape(10,3)

In [155]:
y = np.round((x-np.min(x, axis = 0))/(np.max(x, axis = 0)-np.min(x, axis = 0))*10, decimals = 2)
print(y)

[[ 0.72  2.22  8.02]
 [ 8.87  8.33  5.68]
 [ 0.93 10.    6.17]
 [10.    5.44  7.9 ]
 [10.    1.11  3.95]
 [ 2.37  1.22  7.16]
 [ 5.88  1.33  0.86]
 [ 9.48  9.11  0.  ]
 [ 2.68  0.    3.58]
 [ 0.    1.   10.  ]]


#### NP.9:

Task: Replace all NaN values in the matrix `x` with 0.

Desired output: 

~~~
[[ 8. 24. 67.]
 [87. 79.  0.]
 [10.  0. 52.]
 [ 0. 53. 66.]]
~~~

In [156]:
# do not modify
np.random.seed(100)
x = np.random.randint(100,size = 12).reshape(4,3).astype('float')
row = np.array([1, 2, 3])
col = np.array([2, 1, 0])
x[row, col] = np.nan

In [157]:
no_nans = np.nan_to_num(x)
print(no_nans)

[[ 8. 24. 67.]
 [87. 79.  0.]
 [10.  0. 52.]
 [ 0. 53. 66.]]
